config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :assets do
    resources :histories
  end
  
  resources :transactions

  root 'assets#index'
end

app/models/asset.rb
# == Schema Information
#
# Table name: assets
#
#  id            :integer          not null, primary key
#  name          :string           not null
#  purchase_date :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Asset < ActiveRecord::Base
  validates :name, presence: true

  has_many :histories, dependent: :destroy  
end

app/models/history.rb
# == Schema Information
#
# Table name: histories
#
#  id          :integer          not null, primary key
#  asset_id    :integer
#  description :string           not null
#  created_at  :datetime         not null
#

class History < ActiveRecord::Base
  belongs_to :asset

  validates :description, presence: true
  validates :date_history, presence: true
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id               :integer          not null, primary key
#  title            :string           not null
#  date_transaction :datetime
#  price            :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Transaction < ActiveRecord::Base
  has_attached_file :attachment, styles: { thumb: "100x100>" }, default_url: "/images/noimagefound.jpg"
  do_not_validate_attachment_file_type :attachment

  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy]

  def index
    @assets = Asset.all  
  end

  def show    
    @history = @asset.histories.new
  end

  def new
    @asset = Asset.new  
  end

  def create
    @asset = Asset.new(asset_params)  
    if @asset.save
      redirect_to asset_path(@asset), notice: "Asset was successfully created"  
    else
      render "new"  
    end
  end

  def edit
  end

  def update
    if @asset.update(asset_params)
      redirect_to asset_path(@asset), notice: "Asset was successfully updated"  
    else
      render "edit"  
    end
  end

  def destroy
    @asset.destroy
    redirect_to assets_url, notice: "Asset was successfully destroyed"  
  end

  private
    def set_asset
      @asset = Asset.find(params[:id])    
    end

    def asset_params
      params.require(:asset).permit(:name, :purchase_date)
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_asset, only: [:create] 
  def new
    
  end

  def create
    @history = @asset.histories.new(history_params)  
    if @history.save
      redirect_to asset_path(@asset.id), notice: "History was successfully created"
    else
      render "new"
    end  
  end

  private
    def history_params
      params.require(:history).permit(:description, :date_history)  
    end

    def set_asset
      @asset = Asset.find(params[:asset_id])
    end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  # before_action :set_asset_collection, only: [:new, :edit]
  def index
    @transactions = Transaction.all  
  end

  def show  
  end

  def new
    @transaction = Transaction.new  
  end

  def create
    @transaction = Transaction.new(transaction_params)
    if @transaction.save
      redirect_to transaction_path(@transaction), notice: "Transaction was successfully created"  
    else
      render "new"  
    end
  end

  def edit
  end

  def update
    if @transaction.update(transaction_params)  
      redirect_to transaction_path(@transaction), notice: "Transaction was successfully updated"
    else
      render "edit"
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_path, notice: "Transaction was successfully destroyed"  
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])  
    end

    def transaction_params
      params.require(:transaction).permit(:title, :date_transaction, :price, :asset_id, :attachment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assets/_form.html.erb
<%= form_for(@asset) do |f| %>
  <% if @asset.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@asset.errors.count, "error") %> prohibited this project from being saved:</h4>
      <ul>
      <% @asset.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "Asset Name" %>
    <%= f.text_field :name, class: "form-control", placeholder: "Asset Name" %>  
  </div>

  <div class="form-group">
    <%= f.label :purchase_date, "Purchase Date" %>
    <div class='input-group date js-datepicker'>
        <%= f.text_field :purchase_date, strftime: '%-d %B %Y', class: "form-control", placeholder: "Purchase Date" %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/assets/edit.html.erb
<div class="page-header">
  <%= link_to assets_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @asset, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Asset</h1>
</div>

<%= render "form" %>

app/views/assets/index.html.erb
<div class="page-header">
  <%= link_to new_asset_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
        New Asset
    <% end %>
  <h1>Listing Assets</h1>
</div>
<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>No#</th>
        <th>Name</th>
        <th>Purchase Date</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @assets.each_with_index do |asset, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= asset.name %></td>
          <td><%= asset.purchase_date.try(:strftime, "%-d %B %Y") %></td>
          <td><%= link_to "Detail", asset_path(asset) %></td>
          <td><%= link_to "Edit", edit_asset_path(asset) %></td>
          <td><%= link_to "Delete", asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr> 
      <% end %> 
    </tbody>     
  </table>
</div>

app/views/assets/new.html.erb
<div class="page-header">
  <%= link_to root_path, class: 'btn btn-default' do %> 
  <span class="glyphicon glyphicon-list-alt"></span>
  Back
  <% end %>
  <h1>New Asset</h1> 
</div>

<%= render "form" %>

app/views/assets/show.html.erb
<div class="page-header">
  <%= link_to assets_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-all"></span>
    Back
  <% end %>
  <%= link_to edit_asset_path(@asset), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Asset</h1>
</div>

<dl class="dl-horizontal">
  <dt>Asset Name:</dt>
  <dd><%= @asset.name %></dd>  

  <dt>Purchase Date:</dt>
  <dd><%= @asset.purchase_date.try(:strftime, "%-d %B %Y") %></dd>

</dl>
<dl class="dl-horizontal">  
    <dt>Description:</dt>
    <% @asset.histories.each do |a| %>
      <dd><%= a.description %>  <%= a.date_history.try(:strftime, "%-d %B %Y") %></dd>
    <% end %>
</dl>


<%= render "histories/form" %>  

app/views/histories/_form.html.erb
<%= form_for([@asset, @history]) do |f| %> 
  <h2>Add history</h2>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, class: "form-control", placeholder: "Description" %>  
    </div>

    <div class="form-group">
      <%= f.label :date_history, "Date of History" %>
      <div class="input-group date js-datepicker">
        <%= f.text_field :date_history, strftime: "%-d %B %Y", class: "form-control" %> 
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-calendar"></span>  
        </span> 
      </div>  
    </div>

    <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/histories/new.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>Add History</h1>
</div>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Asset Management</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Asset Management", root_path, class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Assets", root_path %></li>
          <li><%= link_to "Transcation", transactions_path %></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>                
              </a>
              <ul class="nav navbar-nav navbar-right">
                <li><%= link_to "Profile #{current_user.email}" %></li>
                <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction, html: { multipart: true }) do |f| %>
  <% if @transaction.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@transaction.errors.count, "error") %>Probohited this project from being saved:</h4>
        <ul>
          <%= @transaction.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul> 
    </div>
  <% end %>


  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title Name" %>  
  </div>

  <div class="form-group">
    <%= f.label :date_transaction, "Date of Transaction" %>
    <div class='input-group date js-datepicker'>
      <%= f.text_field :date_transaction, strftime: '%-d %B %Y', class: "form-control", placeholder: "Date of Transaction" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>  
    </div>  
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control", placeholder: "Price" %>  
  </div>

  <div class="form-group">
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>  
  </div>

  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/transactions/edit.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @transaction, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing Tranasction</h1>
</div>

<%= render "form" %>

app/views/transactions/index.html.erb
<div class="page-header">
  <%= link_to new_transaction_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Transaction
  <% end %>
    <h1>Listing Transaction</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th>No#</th>
        <th>Title</th>
        <th>Date of Transaction</th>
        <th>Price</th>
        <th>Attachment</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>  
    <tbody>
      <% @transactions.each_with_index do |transaction, index| %>  
        <tr>
          <td><%= index + 1 %></td>
          <td><%= transaction.title %></td>
          <td><%= transaction.date_transaction.try(:strftime, "%-d %B %Y") %></td>
          <td><%= transaction.price %></td>
          <% if transaction.attachment_content_type.try(:include?, "image") %>  
            <td><%= image_tag transaction.attachment.url(:thumb) %></td>
          <% else %>
            <td><%= link_to transaction.attachment_file_name, transaction.attachment.url %></td>
          <% end %>
          <td><%= link_to "Show", transaction_path(transaction) %></td>
          <td><%= link_to "Edit", edit_transaction_path(transaction) %></td>
          <td><%= link_to "Delete", transaction, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/transactions/new.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: "btn btn-default" do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New Transaction</h1>
</div>

<%= render "form" %>

app/views/transactions/show.html.erb
<div class="page-header">
  <%= link_to transactions_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-all"></span>
    Back
  <% end %>
  <%= link_to edit_transaction_path(@transaction), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Transaction</h1>
</div>

<dl class="dl-horizontal">
  <dt>Titlte of Transaction:</dt>
  <dd><%= @transaction.title %></dd>  

  <dt>Date of Transaction:</dt>
  <dd><%= @transaction.date_transaction %></dd>

  <dt>Price:</dt>
  <dd><%= @transaction.price %></dd>

  <dt>Attachment:</dt>
  <% if @transaction.attachment_content_type.try(:include?, "image") %>
    <dd><%= image_tag @transaction.attachment.url %></dd>
  <% else %>
    <dd><%= link_to @transaction.attachment_file_name, @transaction.attachment.url %></dd>
  <% end %>
</dl>